<a href="https://colab.research.google.com/github/iqraghori/TMDB-API-Movie-Data-Analysis/blob/main/the_movie_database_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TMDb API Movie Data Analysis**

## Import Libraries

In [1]:
import requests
import pandas as pd
from google.colab import userdata

## API Authentication

In [2]:
TMDB_API = userdata.get('TDBM_API')
#url = f"https://api.themoviedb.org/3/movie/popular?api_key={TMDB_API}&page=500"

# **FETCH MOVIE DATA**

In [3]:
movies = []
for i in range(1, 501):
  url = f"https://api.themoviedb.org/3/movie/popular?api_key={TMDB_API}&page={i}"
  response = requests.get(url)
  data = response.json()
  movies.extend(data['results'])

In [40]:
movies[0]

{'adult': False,
 'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
 'genre_ids': [27],
 'id': 1339713,
 'title': 'Obsession',
 'original_language': 'en',
 'original_title': 'Obsession',
 'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
 'popularity': 592.6272,
 'poster_path': '/6X4qFYBsG3bpWDG2XIKqr04kFJa.jpg',
 'release_date': '2026-05-13',
 'softcore': False,
 'video': False,
 'vote_average': 7.899,
 'vote_count': 468}

## Convert JSON to DataFrame

In [4]:
df = pd.DataFrame(movies)
df.head(2)
df.shape

(10000, 15)

# **DATA CLEANING**

In [5]:
df_movie = df[['id','adult', 'title', 'release_date', 'popularity', 'vote_average', 'vote_count']]
df_movie.head(2)

,id,adult,title,release_date,popularity,vote_average,vote_count
0,1339713,False,Obsession,2026-05-13,592.6272,7.899,468
1,1304313,False,Lee Cronin's The Mummy,2026-04-15,493.1318,8.063,1523

In [6]:
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   adult         10000 non-null  bool
 2   title         10000 non-null  object
 3   release_date  10000 non-null  object
 4   popularity    10000 non-null  float64
 5   vote_average  10000 non-null  float64
 6   vote_count    10000 non-null  int64
dtypes: bool(1), float64(2), int64(2), object(2)
memory usage: 478.6+ KB

In [7]:
df_movie.shape

(10000, 7)

In [32]:
#df_movie['id'].value_counts()[lambda x: x>1] returns a seires not  a dataframe
df_movie[df_movie[['id','title']].duplicated()]
df_movie = df_movie.drop_duplicates(subset=['id','title'])

In [33]:
df_movie.duplicated().sum()

np.int64(0)

In [37]:
df_movie.isnull().sum()

id              0
adult           0
title           0
release_date    0
popularity      0
vote_average    0
vote_count      0
dtype: int64

# **EXPLORATORY DATA ANALYSIS EDA**

# Univariate Analysis

### KDE Plot

### Box Plot removing outliers

# Bivarate Analysis

### Correlation Heatmap

### Scatter Plots

# **ADVANCED EDA**

### Weighted rating (IMDB-style)

### Popularity vs rating paradox

# **FEATURE ENGINEERING / AUGMENTATION**

### Extract year/month/day

### Popularity categories

### Rating categories

## Key Insights